Repository rancher/charts, pull requests merged in 2019-11, with the labels that each got.

#315 HPE FlexVolume Driver Helm Chart v3.1.0
  charts/hpe-flexvolume-driver/hpedev.png
  charts/hpe-flexvolume-driver/v3.1.0/Chart.yaml
  charts/hpe-flexvolume-driver/v3.1.0/README.md
  charts/hpe-flexvolume-driver/v3.1.0/app-readme.md
  charts/hpe-flexvolume-driver/v3.1.0/questions.yml
  charts/hpe-flexvolume-driver/v3.1.0/templates/NOTES.txt
  charts/hpe-flexvolume-driver/v3.1.0/templates/_helpers.tpl
  charts/hpe-flexvolume-driver/v3.1.0/templates/hpe-config.yaml
  charts/hpe-flexvolume-driver/v3.1.0/templates/hpe-doryd-rbac.yaml
  charts/hpe-flexvolume-driver/v3.1.0/templates/hpe-doryd.yaml
  charts/hpe-flexvolume-driver/v3.1.0/templates/hpe-flexvolume-plugin.yaml
  charts/hpe-flexvolume-driver/v3.1.0/templates/hpe-secret.yaml
  charts/hpe-flexvolume-driver/v3.1.0/templates/hpecv-cp.yaml
  charts/hpe-flexvolume-driver/v3.1.0/templates/post-install.yaml
  charts/hpe-flexvolume-driver/v3.1.0/templates/sc.yaml
  charts/hpe-flexvolume-driver/v3.1.0/values.yaml
Labels: partner

#325 Update storageos-operator to version 0.2.15
  proposed/storageos-operator/v0.2.15/Chart.yaml
  proposed/storageos-operator/v0.2.15/LICENSE
  proposed/storageos-operator/v0.2.15/README.md
  proposed/storageos-operator/v0.2.15/app-readme.md
  proposed/storageos-operator/v0.2.15/ci/std-values.yaml
  proposed/storageos-operator/v0.2.15/questions.yml
  proposed/storageos-operator/v0.2.15/templates/NOTES.txt
  proposed/storageos-operator/v0.2.15/templates/_helpers.tpl
  proposed/storageos-operator/v0.2.15/templates/cleanup.yaml
  proposed/storageos-operator/v0.2.15/templates/job_crd.yaml
  proposed/storageos-operator/v0.2.15/templates/nfsserver_crd.yaml
  proposed/storageos-operator/v0.2.15/templates/operator.yaml
  proposed/storageos-operator/v0.2.15/templates/psp.yaml
  proposed/storageos-operator/v0.2.15/templates/rbac.yaml
  proposed/storageos-operator/v0.2.15/templates/secrets.yaml
  proposed/storageos-operator/v0.2.15/templates/service-account.yaml
  proposed/storageos-operator/v0.2.15/templates/storageoscluster_cr.yaml
  proposed/storageos-operator/v0.2.15/templates/storageoscluster_crd.yaml
  proposed/storageos-operator/v0.2.15/templates/storageosupgrade_crd.yaml
  proposed/storageos-operator/v0.2.15/values.yaml
Labels: partner, to-merge

#322 updated questions.yaml to match values.yaml
  charts/traefik/v1.7/questions.yml
Labels: to-merge
